### ISSUE TITLE
Create API keys tied to cloud license

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/plug#11]
Generate temporary cloud license for external collaborators and people participating to training

**Comment by jon-hagg** [comment]
Overview:

Each cloud license is associated with a "pool" which consists of a set of machines. We can create any number of api keys associated with a given cloud license in the [portal](https://cloud.gurobi.com/manager/keys). An api key consists of an `(Access Id, Secret key)` pair which can be copy/pasted into a `gurobi.lic` file, so in effect is equivalent to the license (many to one relationship).

Suggested approach:

To grant a collaborator temporary access to a pool, we can just create an api key for them (in the form of a license file, for convenience) which can be used within the standalone container setup. We can specify out of band the amount of time they should have access, and manually delete the key in the portal to simulate expiration. If we want to get fancy, they also have a [swagger page](https://cloud.gurobi.com/swagger.html) with the api endpoints used by the cloud portal, so we could even automate this process if needed.

**Comment by rouille** [comment]
@kasparm and @jon-hagg, are we still interested in doing this? Or we can close this issue or move it in the backlog?

**Comment by jon-hagg** [comment]
I think we can close it - my understanding is this was just to establish an approach we can use in the future. We don't need to have an issue for each temporary license as that can be tracked elsewhere.
