### ISSUE TITLE
After creating and launching around 330 scenarios using docker, the stored scenario results crashed. 

### ISSUE THREAD

**Issue by yuhaoMSR** [Breakthrough-Energy/plug#23]
# :beetle:
I have checked that this issue has not already been reported.

### Bug summary
After creating and launching around 330 scenarios using docker, the stored scenario results crashed. 
The ScenarioList.csv in mnt/bes/pcm somehow changes to 

> 89,test,comp_c42e29dc-64ee-4f1c-b3b5-927d7d49061f,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:05,
90,test,comp_1ae5bfc7-67fe-4681-b921-fe2ad1d1937a,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:04,
91,test,comp_132fddc3-1f17-49dc-b190-3c129f03ecac,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:05,
92,test,comp_d09c9595-f348-40fb-85c3-737c13f5e0db,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:05,
93,test,comp_3732a5f3-e59c-496a-b25a-a3a10332d0f1,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:04,
94,test,comp_20011abd-757c-466b-8c32-7b39279c40c1,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:04,
95,test,comp_1125348b-7779-4107-b580-e3f00b6a2557,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:05,
96,test,comp_ea300755-52c6-458f-a623-47bd938c52d2,analyze,usa_tamu,Texas,vJan2021,vJan2021,vJan2021,vJan2021,Yes,2016-01-01 00:00:00,2016-01-31 00:00:00,1H,REISE.jl,0:04,
328,,,analyze,,,,,,,,,,,,0:03,
329,,,analyze,,,,,,,,,,,,,
330,,,analyze,,,,,,,,,,,,,
327,,,analyze,,,,,,,,,,,,,
331,,,analyze,,,,,,,,,,,,0:04,
332,,,analyze,,,,,,,,,,,,0:04,
333,,,analyze,,,,,,,,,,,,0:03,

As you can see, the previously listed scenarios from 97 to 327 are removed and the scenarios after 328 are also in the wrong format.

The files in mnt/bes/pcm/data and mnt/bes/pcm still look reasonable.

### Code for reproduction
Just create and launch more than 330 scenarios.

### Expected outcome
It is expected that we can run as many scenarios as we can.

### Environment
* Operating system: Linux on Azure virtual machine
* plug revision: 291046c79642607b6adb194ad6719615119ece87
* Docker version: Docker version 20.10.6+azure; docker-compose version 1.23.2
* Docker image information:
  ghcr.io/breakthrough-energy/postreise   latest    24d0dd3d222f   6 days ago     2.19GB
  ghcr.io/breakthrough-energy/reisejl     latest    6f7615b61cef   2 weeks ago    2.26GB

### Additional context
The memory usage of docker is like the following:

> CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
a3f32f6140b1   reisejl   0.02%     6.43GiB / 141.6GiB    4.54%     484kB / 509kB     4.96MB / 91.7MB   376
5a4aeb016b5c   client    0.00%     1.266GiB / 141.6GiB   0.89%     29.4MB / 5.15MB   11.8MB / 46.2MB   1

This situation has happened a few times, one on my local computer and twice on Azure virtual machine.

**Comment by yuhaoMSR** [comment]
The memory usage of docker is like the following:

> CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
a3f32f6140b1   reisejl   0.02%     6.43GiB / 141.6GiB    4.54%     484kB / 509kB     4.96MB / 91.7MB   376
5a4aeb016b5c   client    0.00%     1.266GiB / 141.6GiB   0.89%     29.4MB / 5.15MB   11.8MB / 46.2MB   1

**Comment by jon-hagg** [comment]
Sorry for the trouble. It sounds like you could be running into a resource limitation somewhere, either the volume size allowed by docker (couldn't find docs about this, but could be a thing), or hard drive space. Curious how big is the disk allocated to your virtual machine? Another thing to check would be `docker system df` to see how much space the volume is using. You might be the first person to run this many scenarios using docker, so this is new territory.

**Comment by yuhaoMSR** [comment]
> Sorry for the trouble. It sounds like you could be running into a resource limitation somewhere, either the volume size allowed by docker (couldn't find docs about this, but could be a thing), or hard drive space. Curious how big is the disk allocated to your virtual machine? Another thing to check would be `docker system df` to see how much space the volume is using. You might be the first person to run this many scenarios using docker, so this is new territory.

Thank you very much for the response! 

1. The disk allocated to the virtual machine is 150 Size (GiB) with Max IOPS 1100, max throughput(MBps) 125.

2. Currently, I have 180 scenarios of Texas grid with 1 month period in my docker. `docker system df` returns
> TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          3         3         3.523GB   933.7MB (26%)
Containers      3         2         38.73MB   0B (0%)
Local Volumes   1         1         11.29GB   0B (0%)
Build Cache     0         0         0B        0B

I hope these information could help locate the issues. Please feel free to let me know if any other information is needed. Thank you again.

**Comment by ahurli** [comment]
Hi Yuhao! I have a couple more questions to try and help us figure out how this issue happens:
1. Are you running these scenario concurrently or sequentially? If concurrently, approximately how many scenarios are you running at the same time?
2. Do you know the last time you had a valid ScenarioList.csv (e.g. when creating Scenario ###, when analyzing Scenario ###)?
3. How did you notice that this file was corrupted (e.g. when trying to analyze Scenario ###)?
4. You mentioned you've run into this issue multiple times already. Are you running the same ~330 scenarios each time, or are they slightly different? Does the ScenarioList break in the same way (i.e. missing lines 97 to 327, and malformed from 328-333), or are the numbers slightly different each time?

Thanks for your patience with us!

**Comment by yuhaoMSR** [comment]
Hi Anna, thank you for these questions.

> 1. Are you running these scenario concurrently or sequentially? If concurrently, approximately how many scenarios are you running at the same time?
Concurrently, i think. What I did is that I have a for loop, inside the each loop, I will have a different change table and then create the new scenario for that new change table. Then, after creating these scenarios sequentially in a for loop, I think the optimization problems are solved concurrently in the background.

Around 100-200 simulations (with Texas grid, 1 month period, 1 hour interval) were created for each for loop.

> 2. Do you know the last time you had a valid ScenarioList.csv (e.g. when creating Scenario ###, when analyzing Scenario ###)?
From my experience, running 150-180 simulations are pretty stable.
I just did not try more than 200 simulations after encountering this issue...

> 3. How did you notice that this file was corrupted (e.g. when trying to analyze Scenario ###)?
The corruption was found by the return of "Scenario().get_scenario_table()", basically, this is what saved in ScenarioList.csv.
The failure error will appear when trying to analyze Scenario ### corrupted in ScenarioList.csv.
The data stored in /mnt/bes/pcm/data and /mnt/bes/pcm/tmp seems not corrupted (I am not 100% sure). 

> 4. You mentioned you've run into this issue multiple times already. Are you running the same ~330 scenarios each time, or are they slightly different? Does the ScenarioList break in the same way (i.e. missing lines 97 to 327, and malformed from 328-333), or are the numbers slightly different each time?

The number of running simulations when corrupting could be different. The same issue also happened once after running around 180 scenarios

Thank you!

**Comment by jon-hagg** [comment]
Just a quick update. I think we have a decent guess as to the problem, as well as a potential workaround, which would be possible with a few code changes. There shouldn't be any issue running the optimization concurrently, but I suspect there are race conditions modifying the ScenarioList csv which would happen as part of the "extraction" process once the simulation is complete. This currently defaults to happen automatically, but if we change that and allow extraction to happen sequentially, it might eliminate that risk. Will discuss with the team and keep you posted. Thanks again for the patience.

**Comment by jon-hagg** [comment]
Hi @yuhaoMSR, we've merged the code changes discussed previously, enabling the post-simulation extraction to be done separately, not in parallel. If you'd like to try it out, you can `docker pull` the latest images for `powersimdata` and `reisejl`, then in your script, do the following:
1) add the `extract_data=False` argument to your call to `scenario.launch_simulation`
2) in a single threaded loop, call `scenario.extract_simulation_output()` on each one once it's finished. You could check this using `scenario.check_progress()['status'] == 'finished'`

I believe this will solve the issue, but the only real way to know is to try it, so I look forward to hearing your experience.

**Comment by yuhaoMSR** [comment]
Hi @jon-hagg, thank you very much for fixing this issue. I could run and store more than 600 scenarios now. But the problem is that the state of all scenarios are now "execute" instead of "analyze" after the simulations are actually finished. Could you further check this issue? Thank you very much!

**Comment by jon-hagg** [comment]
@yuhaoMSR I meant to say previously, you would need to docker pull the latest `postreise` image (not `powersimdata` as I said above), or alternatively update your compose file to use `powersimdata` instead for the `client` service. Without that, `extract_simulation_output` will not have an effect. If that all runs successfully but you still see the "execute" state, I would try re instantiating the scenario object - if the value in ScenarioList.csv shows "analyze", that should be correctly reflected in a fresh instance.

**Comment by jon-hagg** [comment]
Sounds like we can close this, let me know if there is any remaining issue @yuhaoMSR

**Comment by yuhaoMSR** [comment]
Thank you for addressing this issue!
