### ISSUE TITLE
Gurobi Academic Licenses cannot be used from within a Docker image

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/plug#8]
I got this feedback from one of our collaborators. The specific error they got was `Problem generating unique host ID for this machine`, and it seems like it may be something that Gurobi does intentionally (see https://stackoverflow.com/a/58666698).

**Comment by kasparm** [comment]
Please us the Web License Service see here https://www.gurobi.com/academia/academic-program-and-licenses/
